arb-dir: lib/l10n
template-arb-file: intl_fa.arb
output-localization-file: app_localizations.dart
preferred-supported-locales: fa
untranslated-messages-file: .dart_tool/flutter_gen/gen_l10n/untranslated.json
