name: behandam
description: A new behandam Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.6.0+360

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  logifan:
    path: ../logifan
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  fluttertoast: ^8.0.8
  logger: ^1.1.0
  json_annotation: ^4.4.0
  sizer: ^2.0.15
  flutter_flavor: ^3.0.1
  velocity_x: ^3.4.0
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.20
  flutter_spinkit: ^5.1.0
  badges: ^2.0.1
  rolling_switch: ^0.0.2
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.0
  dio: ^4.0.5
  persian_number_utility: ^1.1.0
  shamsi_date: ^1.0.0
  file_picker: ^4.5.1
  image_picker: ^0.8.5
  flutter_sound: ^9.2.13
  permission_handler: ^8.2.6
  app_settings: ^4.1.6
  path_provider: ^2.0.2
  open_file: ^3.2.1
  flutter_html: ^3.0.0-alpha.3
  flutter_image_compress: ^1.1.0
  image: ^3.0.2
  persian_datetime_picker: ^2.3.0
  chewie: ^1.3.3
  video_player: ^2.4.2
  syncfusion_flutter_sliders: ^20.1.58
  share_plus: ^4.0.3
  syncfusion_flutter_charts: ^20.1.58+1
  flutter_custom_tabs: ^1.0.3
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  external_app_launcher: ^2.0.2
  awesome_notifications: ^0.0.6+12
  android_intent: ^2.0.2
  device_apps: ^2.2.0
  filesize: ^2.0.1
  open_store: ^0.2.4
  carousel_slider: ^4.1.1
  sms_autofill: ^2.2.0
  expand_widget: ^2.1.0
  expandable: ^5.0.1
  flutter_web_frame: ^0.0.3
  universal_html: ^2.0.8
  touch_mouse_behavior: ^0.0.1
  webviewx: ^0.2.1
  dotted_border: ^2.0.0+2
  event_bus: ^2.0.0
  easy_mask: ^2.0.1


dependency_overrides:
  provider: ^6.0.2
  retrofit: ^3.0.1+1
  webview_flutter: ^3.0.4

dev_dependencies:
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/tab/
    - assets/images/profile/
    - assets/images/diet/
    - assets/images/foodlist/fasting/
    - assets/images/registry/
    - assets/images/physical_report/
    - assets/images/ticket/
    - assets/images/foodlist/
    - assets/images/bill/
    - assets/images/foodlist/share/
    - assets/images/psychology/
    - assets/images/vitrin/
    - assets/images/foodlist/archive/
    - assets/images/foodlist/advice/
    - assets/images/shop/
    - assets/images/foodlist/pregnancy/
    - assets/images/foodlist/ramadan/
  fonts:
    - family: Iransans
      fonts:
        - asset: fonts/iransans.ttf
    - family: Iransans-Bold
      fonts:
        - asset: fonts/iransans_bold.ttf
    - family: Iransans-Ultralight
      fonts:
        - asset: fonts/iransans_ultralight.ttf
    - family: Iransans-light
      fonts:
        - asset: fonts/iransans_light.ttf
    - family: yekan
      fonts:
        - asset: fonts/YekanBakhFaNumMedium.ttf
    - family: yekan_bold
      fonts:
        - asset: fonts/YekanBakhFaNumBold.ttf
    - family: yekan_regular
      fonts:
        - asset: fonts/YekanBakhFaNumRegular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto_05_Medium.ttf
    - family: Roboto_regular
      fonts:
        - asset: fonts/Roboto_04_Regular.ttf
