name: behandam
description: A new behandam Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  logifan:
    path: ../logifan
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  retrofit: ^2.0.1
  logger: ^1.1.0
  json_annotation: ^4.1.0
  sizer: ^2.0.15
  flutter_flavor: ^3.0.1
  velocity_x: ^3.3.0
  persian_number_utility: ^0.3.4
  package_info_plus: ^1.0.6
  shamsi_date: ^0.15.0
  rolling_switch: ^0.0.2
  pin_code_fields: ^7.3.0
  toggle_switch: ^1.2.0

dev_dependencies:
  json_serializable: ^5.0.2
  retrofit_generator: ^2.0.1+1
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/tab/
    - assets/images/registry/
    - assets/images/physical_report/
    - assets/images/diet/
  fonts:
    - family: Iransans
      fonts:
        - asset: fonts/iransans.ttf
    - family: Iransans-Bold
      fonts:
        - asset: fonts/iransans_bold.ttf
    - family: Iransans-Ultralight
      fonts:
        - asset: fonts/iransans_ultralight.ttf