name: behandam
description: A new behandam Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+100

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  logifan:
    path: ../logifan
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  rxdart: ^0.27.6
  shared_preferences: ^2.1.0
  fluttertoast: ^8.0.8
  logger: ^1.1.0
  json_annotation: ^4.7.0
  sizer: ^2.0.15
  flutter_flavor: ^3.0.3
  velocity_x: ^3.6.0
  device_info_plus: 8.0.0
  package_info_plus: 3.0.2
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  badges: ^2.0.1
  rolling_switch: ^0.0.2
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.2
  dio: ^5.1.2
  persian_number_utility: ^1.1.0
  shamsi_date: ^1.0.0
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  app_settings: ^4.1.8
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_html: ^3.0.0-alpha.6
  flutter_image_compress: ^1.1.3
  image: ^3.2.0
  persian_datetime_picker: ^2.5.0
  chewie: ^1.3.6
  video_player: ^2.4.7
  syncfusion_flutter_sliders: ^20.3.48
  share_plus: 6.0.0
  syncfusion_flutter_charts: ^20.3.48
  flutter_custom_tabs: ^1.0.3
  firebase_core: ^2.2.0
  firebase_analytics: ^10.0.5
  firebase_crashlytics: ^3.0.5
  firebase_messaging: ^14.1.0
  external_app_launcher: ^3.1.0
  awesome_notifications: ^0.6.21
  android_intent_plus: ^3.1.9
  device_apps: ^2.2.0
  filesize: ^2.0.1
  open_store: ^0.5.0
  carousel_slider: ^4.2.1
  sms_autofill: ^2.2.0
  expand_widget: ^3.1.0
  expandable: ^5.0.1
  flutter_web_frame: ^0.0.3
  universal_html: ^2.0.8
  touch_mouse_behavior: ^1.0.0
  webviewx: ^0.2.1
  dotted_border: ^2.0.0+2
  event_bus: ^2.0.0
  easy_mask: ^2.0.1
  dio_http2_adapter: ^2.2.0
  scroll_snap_list: ^0.9.1
  scrollable_positioned_list: ^0.3.5
  introduction_screen: ^3.0.2
  country_calling_code_picker: ^2.0.1
  flutter_staggered_grid_view: ^0.6.2
  marquee_widget: ^1.2.0
  android_id: ^0.0.7
  need_resume: ^1.0.6
  public_ip: ^0.1.0
  dart_ipify: ^1.1.1
  alarm: ^1.0.5
  http: ^0.13.6
  pedometer: ^3.0.0
  syncfusion_flutter_gauges: ^20.1.55

dependency_overrides:
  provider: ^6.0.5
  retrofit: ^4.0.1
  xml: ^6.2.2
  ffi: ^2.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.2.1
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/tab/
    - assets/images/profile/
    - assets/images/diet/
    - assets/images/foodlist/fasting/
    - assets/images/registry/
    - assets/images/physical_report/
    - assets/images/ticket/
    - assets/images/foodlist/
    - assets/images/bill/
    - assets/images/foodlist/share/
    - assets/images/psychology/
    - assets/images/vitrin/
    - assets/images/foodlist/archive/
    - assets/images/foodlist/advice/
    - assets/images/foodlist/advice/
    - assets/images/shop/
    - assets/images/pedometer/
    - assets/notif_sound/
  fonts:
    - family: Cairo-regular
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: Cairo-bold
      fonts:
        - asset: fonts/Cairo-Bold.ttf
    - family: Cairo-Ultralight
      fonts:
        - asset: fonts/Cairo-Light.ttf