name: behandam
description: A new behandam Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  logifan:
    path: ../logifan
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  retrofit: ^2.1.0
  logger: ^1.1.0
  json_annotation: ^4.3.0
  sizer: ^2.0.15
  flutter_flavor: ^3.0.1
  velocity_x: ^3.3.0
  device_info_plus: ^3.1.0
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.12
  flutter_spinkit: ^5.1.0
  badges: ^2.0.1
  rolling_switch: ^0.0.2
  pin_code_fields: ^7.3.0
  toggle_switch: ^1.2.0
  country_code_picker: ^2.0.2
  country_currency_pickers: ^2.0.0
  cached_network_image: ^3.1.0
  dio: ^4.0.1
  persian_number_utility: ^1.1.0
  shamsi_date: ^1.0.0
  file_picker: ^4.2.0
  image_picker: ^0.8.4+4
  webview_flutter: ^2.3.0
  flutter_sound_lite: ^8.3.9
  permission_handler: ^8.2.6
  app_settings: 4.1.1
  path_provider: ^2.0.2
  open_file: ^3.2.1
  flutter_html: ^2.1.0
  flutter_image_compress: ^1.1.0
  image: ^3.0.2
  persian_datetime_picker: ^2.3.0
  chewie: ^1.2.0
  video_player: ^2.1.12

dev_dependencies:
  json_serializable: ^6.0.1
  retrofit_generator: ^2.1.0+1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/tab/
    - assets/images/profile/
    - assets/images/diet/
    - assets/images/foodlist/fasting/
    - assets/images/registry/
    - assets/images/physical_report/
    - assets/images/ticket/
    - assets/images/foodlist/
    - assets/images/bill/
    - assets/images/foodlist/share/
    - assets/images/psychology/
    - assets/images/vitrin/
  fonts:
    - family: Iransans
      fonts:
        - asset: fonts/iransans.ttf
    - family: Iransans-Bold
      fonts:
        - asset: fonts/iransans_bold.ttf
    - family: Iransans-Ultralight
      fonts:
        - asset: fonts/iransans_ultralight.ttf